import jsPDF from "jspdf";


export const generateReportPDF = (

report:any,

property:any

)=>{


const doc = new jsPDF();


let y = 40;


const PAGE_HEIGHT = 280;




const COLORS = {

blue:[37,99,235],

dark:[30,41,59],

gray:[100,116,139],

green:[22,163,74],

};







const addHeader = ()=>{


doc.setFillColor(

COLORS.blue[0],

COLORS.blue[1],

COLORS.blue[2]

);


doc.rect(

0,

0,

210,

30,

"F"

);



doc.setTextColor(

255,

255,

255

);



doc.setFont(

"helvetica",

"bold"

);


doc.setFontSize(20);



doc.text(

"PropIntel AI",

20,

14

);





doc.setFontSize(9);


doc.setFont(

"helvetica",

"normal"

);



doc.text(

"Smart Real Estate Intelligence Platform",

20,

22

);



};









const addFooter = ()=>{


doc.setFontSize(8);


doc.setTextColor(

150,

150,

150

);



doc.text(

`Generated by PropIntel AI | Page ${doc.getNumberOfPages()}`,

20,

290

);


};








const checkPage = (

space:number=10

)=>{


if(y + space > PAGE_HEIGHT){


addFooter();


doc.addPage();


addHeader();


y = 40;


}


};









const addSection = (

title:string

)=>{


checkPage(20);



doc.setFont(

"helvetica",

"bold"

);



doc.setFontSize(15);



doc.setTextColor(

COLORS.dark[0],

COLORS.dark[1],

COLORS.dark[2]

);



doc.text(

title,

20,

y

);



y += 10;


};









const addText = (

label:string,

value:any

)=>{


checkPage();



doc.setFontSize(11);



doc.setFont(

"helvetica",

"normal"

);



doc.setTextColor(

COLORS.gray[0],

COLORS.gray[1],

COLORS.gray[2]

);



const text =

`${label}: ${value || "Not Available"}`;



const lines =

doc.splitTextToSize(

text,

165

);





lines.forEach(

(line:string)=>{


checkPage(7);



doc.text(

line,

25,

y

);



y += 7;


}

);


};









const addBulletList = (

title:string,

items:string[]

)=>{


if(!items || items.length===0)

return;




checkPage(15);



doc.setFont(

"helvetica",

"bold"

);


doc.setFontSize(11);



doc.text(

title,

25,

y

);



y += 8;



doc.setFont(

"helvetica",

"normal"

);



items.forEach(

(item)=>{


checkPage(7);



doc.text(

`• ${item}`,

30,

y

);



y += 7;



}

);



};









const addParagraph = (

text:string

)=>{


checkPage(15);



doc.setFontSize(11);



doc.setFont(

"helvetica",

"normal"

);



const lines =

doc.splitTextToSize(

text || "Not Available",

165

);




lines.forEach(

(line:string)=>{


checkPage(7);



doc.text(

line,

25,

y

);



y += 7;


}

);


};









// =========================
// START
// =========================


addHeader();








// =========================
// PROPERTY SNAPSHOT
// =========================


addSection(

"Property Snapshot"

);







// Builder Branding

if(property?.owner){


addText(

"Builder / Firm",

property.owner.companyName ||

property.owner.fullName

);



addText(

"Builder Email",

property.owner.email

);


}







addText(

"Property Name",

property?.title

);



addText(

"Location",

`${property?.city || ""}, ${property?.state || ""}`

);



addText(

"Property Type",

property?.propertyType

);



addText(

"Area",

`${property?.area || 0} sq.ft`

);



addText(

"Price",

`₹ ${Number(property?.price || 0).toLocaleString("en-IN")}`

);









// =========================
// AI SCORE
// =========================


addSection(

"AI Intelligence Score"

);





doc.setFillColor(

220,

252,

231

);



doc.roundedRect(

20,

y,

170,

35,

5,

5,

"F"

);




doc.setTextColor(

COLORS.green[0],

COLORS.green[1],

COLORS.green[2]

);



doc.setFontSize(28);



doc.setFont(

"helvetica",

"bold"

);



doc.text(

`${report?.overallScore || 0}/100`,

30,

y+23

);



y += 50;







addText(

"Risk Level",

report?.riskAnalysis?.riskLevel ||

report?.riskLevel

);



addText(

"Investment Rating",

report?.investmentAnalysis?.investmentRating

);









// =========================
// PROPERTY OVERVIEW
// =========================


addSection(

"Property Overview"

);



addText(

"Condition",

report?.propertyOverview?.condition

);



addText(

"Estimated Age",

report?.propertyOverview?.estimatedAge

);



addText(

"Property Quality",

report?.propertyOverview?.propertyQuality

);









// =========================
// STRUCTURE
// =========================


addSection(

"Structural Analysis"

);



addText(

"Wall Condition",

report?.structuralAnalysis?.wallCondition

);



addText(

"Floor Condition",

report?.structuralAnalysis?.floorCondition

);



addText(

"Ceiling Condition",

report?.structuralAnalysis?.ceilingCondition

);



addText(

"Structural Risk",

report?.structuralAnalysis?.structuralRisk

);









// =========================
// INTERIOR
// =========================


addSection(

"Interior Analysis"

);



addText(

"Paint",

report?.interiorAnalysis?.paintCondition

);



addText(

"Lighting",

report?.interiorAnalysis?.lighting

);



addText(

"Ventilation",

report?.interiorAnalysis?.ventilation

);



addText(

"Cleanliness",

report?.interiorAnalysis?.cleanliness

);









// =========================
// MAINTENANCE
// =========================


addSection(

"Maintenance Insights"

);



addText(

"Estimated Cost",

report?.maintenanceAnalysis?.estimatedMaintenanceCost

);



addBulletList(

"Urgent Repairs",

report?.maintenanceAnalysis?.urgentRepairs || []

);



addBulletList(

"Future Maintenance",

report?.maintenanceAnalysis?.futureMaintenance || []

);









// =========================
// INVESTMENT
// =========================


addSection(

"Investment Analysis"

);



addText(

"Rental Potential",

report?.investmentAnalysis?.rentalPotential

);



addText(

"Resale Potential",

report?.investmentAnalysis?.resalePotential

);



addText(

"Recommendation",

report?.investmentAnalysis?.recommendation

);









// =========================
// RISK
// =========================


addSection(

"Risk Analysis"

);



addText(

"Risk Level",

report?.riskAnalysis?.riskLevel

);



addBulletList(

"Risk Factors",

report?.riskAnalysis?.riskFactors || []

);



addBulletList(

"Concerns",

report?.riskAnalysis?.concerns || []

);









// =========================
// SUMMARY
// =========================


addSection(

"AI Summary"

);



addParagraph(

report?.summary

);









// =========================
// RECOMMENDATIONS
// =========================


addSection(

"AI Recommendations"

);



addBulletList(

"Recommendations",

report?.recommendations || []

);








addFooter();





doc.save(

`${property?.title || "Property"}-PropIntel-AI-Report.pdf`

);



};